name: managed_gen
description: Code generator for managed library
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.4.1
  analyzer: ">=4.4.0 <6.4.0"
  source_gen: ^1.5.0
  managed: ^1.0.0
  code_builder: ^4.10.0
  recase: ^4.1.0
  glob: ^2.1.2
  path: ^1.8.0

dev_dependencies:
  source_gen_test: ^1.0.6
  build_test: ^2.2.2
  test: ^1.25.2

dependency_overrides:
  managed:
    path: ../managed